/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.kth.id2212.hangman.client;

import java.awt.Color;
import java.awt.Component;

/**
 *
 * @author Anestos
 */
public class MainPanel extends javax.swing.JPanel {
    Component connectPanel;
    Component hangmanPanel;
    Component informationPanel;
    HangmanClient hangmanClient;
    /**
     * Creates new form MainPanel
     * @param clientInstance
     */
    public MainPanel(HangmanClient clientInstance) {
        initComponents();
        this.hangmanClient = clientInstance;

        connectPanel = add(new ConnectionPanel(clientInstance, this));
        this.add(connectPanel);
        hangmanPanel = add(new HangmanPanel(clientInstance, this));
        hangmanPanel.setVisible(false);
        this.add(hangmanPanel);
        informationPanel = add(new InformationPanel());
        this.add(informationPanel);
        
    }
    
    public void showGameGui(){
        connectPanel.setVisible(false);
        hangmanPanel.setVisible(true);
        changeInfoLabel(InfoMessage.CONNECTING);
    }
    
    public void changeInfoLabel(String text){
        ((InformationPanel)informationPanel).setLabelText(text);
    }
    
    public void changeWordHint(String text) {
        ((HangmanPanel)hangmanPanel).setLabelText(text);
    }
    
    public void notConnected(String reason){
        ((ConnectionPanel)connectPanel).notConnected();
        changeInfoLabel(InfoMessage.NOT_CONNECTED+". " +reason);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(400, 370));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    void initFocus() {
        ((ConnectionPanel)connectPanel).initFocus();
    }

    void disconnect() {
        hangmanClient.disconnect();
    }

    void setLetterBG(String string, Color color) {
        ((HangmanPanel)hangmanPanel).setLetterBG(string, color);
    }

    void disableGuessButton() {
        ((HangmanPanel)hangmanPanel).disableGuessButton();
    }

    void removeLetterListeners() {
        ((HangmanPanel)hangmanPanel).removeLetterListeners();
    }
}
