/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.kth.id2212.hangman.client;

import java.awt.Component;

/**
 *
 * @author Anestos
 */
public class MainPanel extends javax.swing.JPanel {
    Component connectPanel;
    Component hangmanPanel;
    Component informationPanel;
    /**
     * Creates new form MainPanel
     * @param clientInstance
     */
    public MainPanel(HangmanClient clientInstance) {
        initComponents();

        connectPanel = add(new ConnectionPanel(clientInstance, this));
        this.add(connectPanel);
        hangmanPanel = add(new HangmanPanel(this));
        hangmanPanel.setVisible(false);
        this.add(hangmanPanel);
        informationPanel = add(new InformationPanel());
        this.add(informationPanel);
    }
    
    public void showGameGui(){
        connectPanel.setVisible(false);
        hangmanPanel.setVisible(true);
        changeInfoLabel(InfoMessage.GAME_STARTED);
    }
    
    public void changeInfoLabel(String text){
        ((InformationPanel)informationPanel).setLabelText(text);
    }
    
    public void notConnected(){
        ((ConnectionPanel)connectPanel).notConnected();
        changeInfoLabel(InfoMessage.NOT_CONNECTED);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(400, 370));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
